/*
 * Configuration.
 */

// Fetch.
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_PENDING = 'FETCH_CONFIGURATION_PENDING';
export const FETCH_CONFIGURATION_REJECTED = 'FETCH_CONFIGURATION_REJECTED';
export const FETCH_CONFIGURATION_FULFILLED = 'FETCH_CONFIGURATION_FULFILLED';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const CLOSE_NOTIFICATION_PENDING = 'CLOSE_NOTIFICATION_PENDING';
export const CLOSE_NOTIFICATION_FULFILLED = 'CLOSE_NOTIFICATION_FULFILLED';
export const CONFIRM_NOTIFICATION = 'CONFIRM_NOTIFICATION';
export const CONFIRM_NOTIFICATION_PENDING = 'CONFIRM_NOTIFICATION_PENDING';
export const CONFIRM_NOTIFICATION_FULFILLED = 'CONFIRM_NOTIFICATION_FULFILLED';

/*
 * Logs.
 */
export const OPEN_LOG = 'OPEN_LOG';
export const CLEAR_LOG = 'CLEAR_LOG';

export const SET_FILTER = 'SET_FILTER';

// Fetch.
export const FETCH_LOGS = 'FETCH_LOGS';
export const FETCH_LOGS_PENDING = 'FETCH_LOGS_PENDING';
export const FETCH_LOGS_REJECTED = 'FETCH_LOGS_REJECTED';
export const FETCH_LOGS_FULFILLED = 'FETCH_LOGS_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

